# Generated by Django 4.2.7 on 2025-04-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('question', models.TextField(verbose_name='考试题目')),
                ('standard_answer', models.TextField(blank=True, verbose_name='标准答案')),
            
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('answer', models.TextField(verbose_name='答案内容')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('similarity', models.FloatField(blank=True, null=True, verbose_name='相似度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '学生答案',
                'verbose_name_plural': '学生答案',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'student_name')},
            },
        ),
    ]
